export type AuditAction =
  | "STUDENT_CREATED"
  | "STUDENT_UPDATED"
  | "STUDENT_DEACTIVATED"
  | "PARENT_CREATED"
  | "PARENT_UPDATED"
  | "DOCUMENT_UPLOADED"
  | "DOCUMENT_DELETED"
  | "TIMETABLE_CREATED"
  | "TIMETABLE_UPDATED"
  | "TIMETABLE_DELETED"
  | "ROOM_CREATED"
  | "ROOM_UPDATED"
  | "PERIOD_CREATED"
  | "PERIOD_UPDATED"
  | "SUBSTITUTION_CREATED"
  | "SUBSTITUTION_UPDATED"
  | "SUBSTITUTION_CANCELLED"
  | "ASSIGNMENT_CREATED"
  | "ASSIGNMENT_UPDATED"
  | "ASSIGNMENT_PUBLISHED"
  | "ASSIGNMENT_CLOSED"
  | "ASSIGNMENT_ARCHIVED"
  | "SUBMISSION_CREATED"
  | "SUBMISSION_GRADED"
  | "SUBMISSION_RETURNED"
  | "SUBMISSION_RESUBMISSION_REQUESTED"
  | "RESOURCE_CREATED"
  | "RESOURCE_UPDATED"
  | "RESOURCE_DELETED"
  | "FEE_STRUCTURE_CREATED"
  | "FEE_STRUCTURE_UPDATED"
  | "FEE_STRUCTURE_DEACTIVATED"
  | "FEE_INVOICE_GENERATED"
  | "FEE_INVOICE_UPDATED"
  | "FEE_INVOICE_CANCELLED"
  | "FEE_PAYMENT_COLLECTED"
  | "FEE_PAYMENT_REFUNDED"
  | "DISCOUNT_CREATED"
  | "DISCOUNT_APPROVED"
  | "DISCOUNT_REJECTED"
  | "FEE_SETTINGS_UPDATED";

export type AuditEntityType =
  | "STUDENT"
  | "PARENT"
  | "DOCUMENT"
  | "SCHOOL"
  | "TIMETABLE"
  | "ROOM"
  | "PERIOD"
  | "SUBSTITUTION"
  | "ASSIGNMENT"
  | "SUBMISSION"
  | "RESOURCE"
  | "FEE_STRUCTURE"
  | "FEE_INVOICE"
  | "FEE_PAYMENT"
  | "DISCOUNT"
  | "FEE_SETTINGS";

export interface AuditLog {
  id: string;
  organizationId: string;
  actorId: string;
  actorName: string;
  action: AuditAction;
  entityType: AuditEntityType;
  entityId: string;
  timestamp: string;
  metadata?: Record<string, any>;
}
