import {
  LayoutDashboard,
  GraduationCap,
  UserPlus,
  Building2,
  Users,
  Calendar,
  Layers,
  BookOpen,
  UserCheck,
  PhoneCall,
  FileCheck,
  CheckCircle2,
  Clock,
  MessageSquare,
  FileText,
  Settings,
  SlidersHorizontal,
  User,
  ClipboardCheck,
  CalendarDays,
  FileSpreadsheet,
  CreditCard,
  Receipt,
  Percent,
  AlertCircle,
  Wallet,
  Edit3,
  Trophy,
  Megaphone,
  Bell,
  Mail,
  History,
  Briefcase,
  BookMarked,
  Bookmark,
  Library as LibraryIcon,
  Bus,
  Route as RouteIcon,
  MapPin,
  Navigation as NavigationIcon,
  Wrench,
  Boxes,
  Package,
  PackagePlus,
  PackageMinus,
  ArrowLeftRight,
  Truck,
  ShoppingCart,
  Bed,
  Plane,
  type LucideIcon,
} from "lucide-react";

export interface NavItemConfig {
  id: string;
  label: string;
  icon: LucideIcon;
  route: string;
  section: string;
  permission?: string;
  children?: NavItemConfig[];
}

export interface NavSectionConfig {
  title: string;
  items: NavItemConfig[];
}

export const navigationConfig: NavSectionConfig[] = [
  {
    title: "Core",
    items: [
      {
        id: "core-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/dashboard",
        section: "Core",
        permission: "dashboard.view",
      },
    ],
  },
  {
    title: "Student Management",
    items: [
      {
        id: "students-directory",
        label: "Students",
        icon: GraduationCap,
        route: "/students",
        section: "Student Management",
        permission: "students.view",
      },
      {
        id: "students-new",
        label: "Enroll Student",
        icon: UserPlus,
        route: "/students/new",
        section: "Student Management",
        permission: "students.create",
      },
      {
        id: "students-promotions",
        label: "Student Promotions",
        icon: Building2,
        route: "/students/promotions",
        section: "Student Management",
        permission: "students.edit",
      },
      {
        id: "parents-directory",
        label: "Parents & Guardians",
        icon: Users,
        route: "/parents",
        section: "Student Management",
        permission: "parents.view",
      },
    ],
  },
  {
    title: "Academics",
    items: [
      {
        id: "academic-sessions",
        label: "Academic Sessions",
        icon: Calendar,
        route: "/academics/sessions",
        section: "Academics",
        permission: "academics.view",
      },
      {
        id: "academic-classes",
        label: "Classes",
        icon: GraduationCap,
        route: "/academics/classes",
        section: "Academics",
        permission: "academics.view",
      },
      {
        id: "academic-sections",
        label: "Sections",
        icon: Layers,
        route: "/academics/sections",
        section: "Academics",
        permission: "academics.view",
      },
      {
        id: "academic-subjects",
        label: "Subjects",
        icon: BookOpen,
        route: "/academics/subjects",
        section: "Academics",
        permission: "academics.view",
      },
      {
        id: "academic-teachers",
        label: "Teachers",
        icon: Users,
        route: "/academics/teachers",
        section: "Academics",
        permission: "teachers.view",
      },
      {
        id: "academic-assignments",
        label: "Assignments",
        icon: UserCheck,
        route: "/academics/assignments",
        section: "Academics",
        permission: "academics.assign",
      },
      {
        id: "academic-settings",
        label: "Settings",
        icon: Settings,
        route: "/academics/settings",
        section: "Academics",
        permission: "academics.settings",
      },
    ],
  },
  {
    title: "Admissions & CRM",
    items: [
      {
        id: "admissions-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/admissions",
        section: "Admissions",
        permission: "admissions.dashboard.view",
      },
      {
        id: "admissions-enquiries",
        label: "Enquiries",
        icon: PhoneCall,
        route: "/admissions/enquiries",
        section: "Admissions",
        permission: "enquiries.view",
      },
      {
        id: "admissions-followups",
        label: "Follow-ups",
        icon: Clock,
        route: "/admissions/follow-ups",
        section: "Admissions",
        permission: "followups.view",
      },
      {
        id: "admissions-applications",
        label: "Applications",
        icon: FileCheck,
        route: "/admissions/applications",
        section: "Admissions",
        permission: "applications.view",
      },
      {
        id: "admissions-documents",
        label: "Documents",
        icon: FileText,
        route: "/admissions/documents",
        section: "Admissions",
        permission: "documents.view",
      },
      {
        id: "admissions-verification",
        label: "Verification",
        icon: UserCheck,
        route: "/admissions/verification",
        section: "Admissions",
        permission: "documents.verify",
      },
      {
        id: "admissions-admitted",
        label: "Admitted Students",
        icon: CheckCircle2,
        route: "/admissions/admitted",
        section: "Admissions",
        permission: "admissions.view",
      },
      {
        id: "admissions-waitlist",
        label: "Waitlist",
        icon: Users,
        route: "/admissions/waitlist",
        section: "Admissions",
        permission: "applications.waitlist",
      },
      {
        id: "admissions-campaigns",
        label: "Campaigns",
        icon: Megaphone,
        route: "/admissions/campaigns",
        section: "Admissions",
        permission: "campaigns.view",
      },
      {
        id: "admissions-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/admissions/reports",
        section: "Admissions",
        permission: "admissions.reports.view",
      },
      {
        id: "admissions-settings",
        label: "Settings",
        icon: Settings,
        route: "/admissions/settings",
        section: "Admissions",
        permission: "admissions.settings",
      },
    ],
  },
  {
    title: "Attendance",
    items: [
      {
        id: "attendance-dashboard",
        label: "Attendance Dashboard",
        icon: LayoutDashboard,
        route: "/attendance",
        section: "Attendance",
        permission: "attendance.dashboard.view",
      },
      {
        id: "attendance-students",
        label: "Student Attendance",
        icon: ClipboardCheck,
        route: "/attendance/students",
        section: "Attendance",
        permission: "attendance.view",
      },
      {
        id: "attendance-staff",
        label: "Staff Attendance",
        icon: UserCheck,
        route: "/attendance/staff",
        section: "Attendance",
        permission: "staffAttendance.view",
      },
      {
        id: "attendance-leave",
        label: "Leave Management",
        icon: CalendarDays,
        route: "/attendance/leave",
        section: "Attendance",
        permission: "leave.view",
      },
      {
        id: "attendance-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/attendance/reports",
        section: "Attendance",
        permission: "attendance.reports.view",
      },
      {
        id: "attendance-settings",
        label: "Settings",
        icon: Settings,
        route: "/attendance/settings",
        section: "Attendance",
        permission: "attendance.settings",
      },
    ],
  },
  {
    title: "Timetable",
    items: [
      {
        id: "timetable-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/timetable",
        section: "Timetable",
        permission: "timetable.view",
      },
      {
        id: "timetable-classes",
        label: "Class Timetable",
        icon: GraduationCap,
        route: "/timetable/classes",
        section: "Timetable",
        permission: "timetable.view",
      },
      {
        id: "timetable-teachers",
        label: "Teacher Timetable",
        icon: Users,
        route: "/timetable/teachers",
        section: "Timetable",
        permission: "timetable.view",
      },
      {
        id: "timetable-rooms",
        label: "Room Timetable",
        icon: Building2,
        route: "/timetable/rooms",
        section: "Timetable",
        permission: "timetable.manageRooms",
      },
      {
        id: "timetable-create",
        label: "Create Timetable",
        icon: SlidersHorizontal,
        route: "/timetable/create",
        section: "Timetable",
        permission: "timetable.create",
      },
      {
        id: "timetable-substitutions",
        label: "Substitutions",
        icon: UserCheck,
        route: "/timetable/substitutions",
        section: "Timetable",
        permission: "timetable.manageSubstitutions",
      },
      {
        id: "timetable-periods",
        label: "Periods",
        icon: Clock,
        route: "/timetable/periods",
        section: "Timetable",
        permission: "timetable.managePeriods",
      },
      {
        id: "timetable-settings",
        label: "Settings",
        icon: Settings,
        route: "/timetable/settings",
        section: "Timetable",
        permission: "timetable.settings",
      },
    ],
  },
  {
    title: "Academic Work",
    items: [
      {
        id: "academic-work-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/academic-work",
        section: "Academic Work",
        permission: "academicWork.dashboard.view",
      },
      {
        id: "academic-work-assignments",
        label: "Assignments",
        icon: FileText,
        route: "/academic-work/assignments",
        section: "Academic Work",
        permission: "assignments.view",
      },
      {
        id: "academic-work-homework",
        label: "Homework",
        icon: BookOpen,
        route: "/academic-work/homework",
        section: "Academic Work",
        permission: "assignments.view",
      },
      {
        id: "academic-work-classwork",
        label: "Classwork",
        icon: Layers,
        route: "/academic-work/classwork",
        section: "Academic Work",
        permission: "assignments.view",
      },
      {
        id: "academic-work-submissions",
        label: "Submissions",
        icon: ClipboardCheck,
        route: "/academic-work/submissions",
        section: "Academic Work",
        permission: "submissions.view",
      },
      {
        id: "academic-work-grading",
        label: "Grading",
        icon: CheckCircle2,
        route: "/academic-work/grading",
        section: "Academic Work",
        permission: "submissions.grade",
      },
      {
        id: "academic-work-resources",
        label: "Resources",
        icon: FileSpreadsheet,
        route: "/academic-work/resources",
        section: "Academic Work",
        permission: "resources.view",
      },
      {
        id: "academic-work-settings",
        label: "Settings",
        icon: Settings,
        route: "/academic-work/settings",
        section: "Academic Work",
        permission: "academicWork.settings",
      },
    ],
  },
  {
    title: "Fees & Finance",
    items: [
      {
        id: "fees-dashboard",
        label: "Fees Dashboard",
        icon: LayoutDashboard,
        route: "/fees",
        section: "Fees & Finance",
        permission: "fees.dashboard.view",
      },
      {
        id: "fees-structure",
        label: "Fee Structure",
        icon: Layers,
        route: "/fees/structure",
        section: "Fees & Finance",
        permission: "feeStructure.view",
      },
      {
        id: "fees-students",
        label: "Student Fees",
        icon: Users,
        route: "/fees/students",
        section: "Fees & Finance",
        permission: "fees.view",
      },
      {
        id: "fees-collect",
        label: "Collect Fees",
        icon: CreditCard,
        route: "/fees/collect",
        section: "Fees & Finance",
        permission: "fees.collect",
      },
      {
        id: "fees-payments",
        label: "Payments",
        icon: Receipt,
        route: "/fees/payments",
        section: "Fees & Finance",
        permission: "payments.view",
      },
      {
        id: "fees-defaulters",
        label: "Defaulters",
        icon: AlertCircle,
        route: "/fees/defaulters",
        section: "Fees & Finance",
        permission: "fees.view",
      },
      {
        id: "fees-discounts",
        label: "Discounts",
        icon: Percent,
        route: "/fees/discounts",
        section: "Fees & Finance",
        permission: "discounts.view",
      },
      {
        id: "fees-receipts",
        label: "Receipts",
        icon: FileText,
        route: "/fees/receipts",
        section: "Fees & Finance",
        permission: "receipts.view",
      },
      {
        id: "fees-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/fees/reports",
        section: "Fees & Finance",
        permission: "fees.reports.view",
      },
      {
        id: "fees-settings",
        label: "Settings",
        icon: Settings,
        route: "/fees/settings",
        section: "Fees & Finance",
        permission: "fees.settings",
      },
    ],
  },
  {
    title: "Examinations",
    items: [
      {
        id: "exams-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/exams",
        section: "Examinations",
        permission: "exams.dashboard.view",
      },
      {
        id: "exams-list",
        label: "Exams",
        icon: GraduationCap,
        route: "/exams/list",
        section: "Examinations",
        permission: "exams.view",
      },
      {
        id: "exams-schedule",
        label: "Exam Schedule",
        icon: Calendar,
        route: "/exams/schedule",
        section: "Examinations",
        permission: "examSchedule.view",
      },
      {
        id: "exams-marks",
        label: "Marks Entry",
        icon: Edit3,
        route: "/exams/marks",
        section: "Examinations",
        permission: "marks.view",
      },
      {
        id: "exams-results",
        label: "Result Processing",
        icon: Layers,
        route: "/exams/results",
        section: "Examinations",
        permission: "results.view",
      },
      {
        id: "exams-report-cards",
        label: "Report Cards",
        icon: FileText,
        route: "/exams/report-cards",
        section: "Examinations",
        permission: "reportCards.view",
      },
      {
        id: "exams-rankings",
        label: "Rankings",
        icon: Trophy,
        route: "/exams/rankings",
        section: "Examinations",
        permission: "rankings.view",
      },
      {
        id: "exams-settings",
        label: "Settings",
        icon: Settings,
        route: "/exams/settings",
        section: "Examinations",
        permission: "exam.settings",
      },
    ],
  },
  {
    title: "Communication",
    items: [
      {
        id: "comm-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/communication",
        section: "Communication",
        permission: "communication.dashboard.view",
      },
      {
        id: "comm-announcements",
        label: "Announcements",
        icon: Megaphone,
        route: "/communication/announcements",
        section: "Communication",
        permission: "announcements.view",
      },
      {
        id: "comm-notices",
        label: "Notices",
        icon: FileText,
        route: "/communication/notices",
        section: "Communication",
        permission: "notices.view",
      },
      {
        id: "comm-messages",
        label: "Messages",
        icon: MessageSquare,
        route: "/communication/messages",
        section: "Communication",
        permission: "messages.view",
      },
      {
        id: "comm-templates",
        label: "Templates",
        icon: Layers,
        route: "/communication/templates",
        section: "Communication",
        permission: "templates.view",
      },
      {
        id: "comm-notifications",
        label: "Notifications",
        icon: Bell,
        route: "/communication/notifications",
        section: "Communication",
        permission: "notifications.view",
      },
      {
        id: "comm-history",
        label: "History",
        icon: History,
        route: "/communication/history",
        section: "Communication",
        permission: "communication.history.view",
      },
      {
        id: "comm-settings",
        label: "Settings",
        icon: Settings,
        route: "/communication/settings",
        section: "Communication",
        permission: "communication.settings",
      },
    ],
  },
  {
    title: "Parent-Teacher Meetings",
    items: [
      {
        id: "ptm-dashboard",
        label: "PTM Dashboard",
        icon: LayoutDashboard,
        route: "/ptm",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-events",
        label: "PTM Events",
        icon: Calendar,
        route: "/ptm/events",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-slots",
        label: "Time Slots",
        icon: Clock,
        route: "/ptm/slots",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-appointments",
        label: "Appointments",
        icon: CalendarCheck,
        route: "/ptm/appointments",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-availability",
        label: "Teacher Availability",
        icon: Users,
        route: "/ptm/availability",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-reports",
        label: "Reports",
        icon: FileText,
        route: "/ptm/reports",
        section: "Parent-Teacher Meetings",
        permission: "dashboard.view",
      },
      {
        id: "ptm-settings",
        label: "Settings",
        icon: Settings,
        route: "/ptm/settings",
        section: "Parent-Teacher Meetings",
        permission: "settings.view",
      },
    ],
  },
  {
    title: "Certificates & Documents",
    items: [
      {
        id: "doc-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/documents",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-certificates",
        label: "Certificates",
        icon: Award,
        route: "/documents/certificates",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-templates",
        label: "Templates",
        icon: Layers,
        route: "/documents/templates",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-generate",
        label: "Issue Certificate",
        icon: FileCheck,
        route: "/documents/generate",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-id-cards",
        label: "ID Cards",
        icon: CreditCard,
        route: "/documents/id-cards",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-bulk",
        label: "Bulk Generation",
        icon: FileText,
        route: "/documents/bulk",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-issued",
        label: "Issued Ledger",
        icon: History,
        route: "/documents/issued",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-verification",
        label: "Verification",
        icon: ShieldCheck,
        route: "/documents/verification",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-reports",
        label: "Reports",
        icon: FileText,
        route: "/documents/reports",
        section: "Certificates & Documents",
        permission: "dashboard.view",
      },
      {
        id: "doc-settings",
        label: "Settings",
        icon: Settings,
        route: "/documents/settings",
        section: "Certificates & Documents",
        permission: "settings.view",
      },
    ],
  },
  {
    title: "Front Office",
    items: [
      {
        id: "fo-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/front-office",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-visitors",
        label: "Visitors",
        icon: Users,
        route: "/front-office/visitors",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-gate-passes",
        label: "Gate Passes",
        icon: Ticket,
        route: "/front-office/gate-passes",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-appointments",
        label: "Appointments",
        icon: CalendarCheck,
        route: "/front-office/appointments",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-calls",
        label: "Phone Calls",
        icon: PhoneCall,
        route: "/front-office/calls",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-enquiries",
        label: "Admission Enquiries",
        icon: HelpCircle,
        route: "/front-office/enquiries",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-correspondence",
        label: "Correspondence",
        icon: Mail,
        route: "/front-office/correspondence",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-tasks",
        label: "Reception Tasks",
        icon: CheckSquare,
        route: "/front-office/tasks",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-reports",
        label: "Reports",
        icon: FileText,
        route: "/front-office/reports",
        section: "Front Office",
        permission: "dashboard.view",
      },
      {
        id: "fo-settings",
        label: "Settings",
        icon: Settings,
        route: "/front-office/settings",
        section: "Front Office",
        permission: "settings.view",
      },
    ],
  },
  {
    title: "Hostel Management",
    items: [
      {
        id: "hostel-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/hostel",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-hostels",
        label: "Hostels",
        icon: Building2,
        route: "/hostel/hostels",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-buildings",
        label: "Buildings",
        icon: Building2,
        route: "/hostel/buildings",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-floors",
        label: "Floors",
        icon: Layers,
        route: "/hostel/floors",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-rooms",
        label: "Rooms",
        icon: Bed,
        route: "/hostel/rooms",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-beds",
        label: "Beds Inventory",
        icon: Bed,
        route: "/hostel/beds",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-students",
        label: "Boarding Students",
        icon: Users,
        route: "/hostel/students",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-allocations",
        label: "Bed Allocations",
        icon: Bed,
        route: "/hostel/allocations",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-attendance",
        label: "Night Roll Call",
        icon: ClipboardCheck,
        route: "/hostel/attendance",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-leave",
        label: "Leave & Out-Pass",
        icon: Plane,
        route: "/hostel/leave",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-visitors",
        label: "Hostel Visitors",
        icon: Users,
        route: "/hostel/visitors",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-complaints",
        label: "Complaints",
        icon: AlertCircle,
        route: "/hostel/complaints",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-maintenance",
        label: "Maintenance",
        icon: Wrench,
        route: "/hostel/maintenance",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-fees",
        label: "Hostel Fees",
        icon: CreditCard,
        route: "/hostel/fees",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-reports",
        label: "Reports",
        icon: FileText,
        route: "/hostel/reports",
        section: "Hostel Management",
        permission: "hostel.view",
      },
      {
        id: "hostel-settings",
        label: "Settings",
        icon: Settings,
        route: "/hostel/settings",
        section: "Hostel Management",
        permission: "settings.view",
      },
    ],
  },
  {
    title: "Staff & HR",
    items: [
      {
        id: "hr-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/hr",
        section: "Staff & HR",
        permission: "hr.dashboard.view",
      },
      {
        id: "hr-staff",
        label: "Staff Directory",
        icon: Users,
        route: "/hr/staff",
        section: "Staff & HR",
        permission: "staff.view",
      },
      {
        id: "hr-departments",
        label: "Departments",
        icon: Building2,
        route: "/hr/departments",
        section: "Staff & HR",
        permission: "departments.view",
      },
      {
        id: "hr-designations",
        label: "Designations",
        icon: Briefcase,
        route: "/hr/designations",
        section: "Staff & HR",
        permission: "designations.view",
      },
      {
        id: "hr-attendance",
        label: "Staff Attendance",
        icon: ClipboardCheck,
        route: "/hr/attendance",
        section: "Staff & HR",
        permission: "staffAttendance.view",
      },
      {
        id: "hr-leave",
        label: "Leave Management",
        icon: CalendarDays,
        route: "/hr/leave",
        section: "Staff & HR",
        permission: "leave.view",
      },
      {
        id: "hr-documents",
        label: "Documents",
        icon: FileText,
        route: "/hr/documents",
        section: "Staff & HR",
        permission: "staffDocuments.view",
      },
      {
        id: "hr-payroll",
        label: "Payroll",
        icon: CreditCard,
        route: "/hr/payroll",
        section: "Staff & HR",
        permission: "payroll.view",
      },
      {
        id: "hr-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/hr/reports",
        section: "Staff & HR",
        permission: "hr.reports.view",
      },
      {
        id: "hr-settings",
        label: "Settings",
        icon: Settings,
        route: "/hr/settings",
        section: "Staff & HR",
        permission: "hr.settings",
      },
    ],
  },
  {
    title: "Library",
    items: [
      {
        id: "lib-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/library",
        section: "Library",
        permission: "library.dashboard.view",
      },
      {
        id: "lib-books",
        label: "Books",
        icon: BookOpen,
        route: "/library/books",
        section: "Library",
        permission: "library.books.view",
      },
      {
        id: "lib-categories",
        label: "Categories",
        icon: Layers,
        route: "/library/categories",
        section: "Library",
        permission: "library.categories.manage",
      },
      {
        id: "lib-authors",
        label: "Authors",
        icon: Users,
        route: "/library/authors",
        section: "Library",
        permission: "library.authors.manage",
      },
      {
        id: "lib-publishers",
        label: "Publishers",
        icon: Building2,
        route: "/library/publishers",
        section: "Library",
        permission: "library.publishers.manage",
      },
      {
        id: "lib-members",
        label: "Members",
        icon: UserCheck,
        route: "/library/members",
        section: "Library",
        permission: "library.members.view",
      },
      {
        id: "lib-transactions",
        label: "Issue / Return",
        icon: BookMarked,
        route: "/library/transactions",
        section: "Library",
        permission: "library.issue",
      },
      {
        id: "lib-reservations",
        label: "Reservations",
        icon: Bookmark,
        route: "/library/reservations",
        section: "Library",
        permission: "library.reservations.view",
      },
      {
        id: "lib-fines",
        label: "Fines",
        icon: Receipt,
        route: "/library/fines",
        section: "Library",
        permission: "library.fines.view",
      },
      {
        id: "lib-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/library/reports",
        section: "Library",
        permission: "library.reports.view",
      },
      {
        id: "lib-settings",
        label: "Settings",
        icon: Settings,
        route: "/library/settings",
        section: "Library",
        permission: "library.settings",
      },
    ],
  },
  {
    title: "Transport",
    items: [
      {
        id: "transport-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/transport",
        section: "Transport",
        permission: "transport.dashboard.view",
      },
      {
        id: "transport-vehicles",
        label: "Vehicles",
        icon: Bus,
        route: "/transport/vehicles",
        section: "Transport",
        permission: "vehicles.view",
      },
      {
        id: "transport-routes",
        label: "Routes",
        icon: RouteIcon,
        route: "/transport/routes",
        section: "Transport",
        permission: "routes.view",
      },
      {
        id: "transport-stops",
        label: "Stops",
        icon: MapPin,
        route: "/transport/stops",
        section: "Transport",
        permission: "stops.view",
      },
      {
        id: "transport-drivers",
        label: "Drivers",
        icon: UserCheck,
        route: "/transport/drivers",
        section: "Transport",
        permission: "drivers.view",
      },
      {
        id: "transport-assignments",
        label: "Assignments",
        icon: NavigationIcon,
        route: "/transport/assignments",
        section: "Transport",
        permission: "transport.assign",
      },
      {
        id: "transport-trips",
        label: "Trips",
        icon: Clock,
        route: "/transport/trips",
        section: "Transport",
        permission: "trips.view",
      },
      {
        id: "transport-students",
        label: "Student Transport",
        icon: Users,
        route: "/transport/students",
        section: "Transport",
        permission: "transport.assign",
      },
      {
        id: "transport-maintenance",
        label: "Maintenance",
        icon: Wrench,
        route: "/transport/maintenance",
        section: "Transport",
        permission: "maintenance.view",
      },
      {
        id: "transport-fees",
        label: "Transport Fees",
        icon: Receipt,
        route: "/transport/fees",
        section: "Transport",
        permission: "transport.fees.view",
      },
      {
        id: "transport-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/transport/reports",
        section: "Transport",
        permission: "transport.reports.view",
      },
      {
        id: "transport-settings",
        label: "Settings",
        icon: Settings,
        route: "/transport/settings",
        section: "Transport",
        permission: "transport.settings",
      },
    ],
  },
  {
    title: "Inventory & Assets",
    items: [
      {
        id: "inv-dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        route: "/inventory",
        section: "Inventory",
        permission: "inventory.dashboard.view",
      },
      {
        id: "inv-items",
        label: "Inventory Items",
        icon: Package,
        route: "/inventory/items",
        section: "Inventory",
        permission: "inventory.items.view",
      },
      {
        id: "inv-assets",
        label: "Assets",
        icon: Boxes,
        route: "/inventory/assets",
        section: "Inventory",
        permission: "inventory.assets.view",
      },
      {
        id: "inv-categories",
        label: "Categories",
        icon: Layers,
        route: "/inventory/categories",
        section: "Inventory",
        permission: "inventory.settings",
      },
      {
        id: "inv-stock-in",
        label: "Stock In",
        icon: PackagePlus,
        route: "/inventory/stock-in",
        section: "Inventory",
        permission: "inventory.items.adjust",
      },
      {
        id: "inv-stock-out",
        label: "Stock Out",
        icon: PackageMinus,
        route: "/inventory/stock-out",
        section: "Inventory",
        permission: "inventory.items.adjust",
      },
      {
        id: "inv-transfers",
        label: "Transfers",
        icon: ArrowLeftRight,
        route: "/inventory/transfers",
        section: "Inventory",
        permission: "inventory.assets.transfer",
      },
      {
        id: "inv-vendors",
        label: "Vendors",
        icon: Truck,
        route: "/inventory/vendors",
        section: "Inventory",
        permission: "inventory.vendors.view",
      },
      {
        id: "inv-po",
        label: "Purchase Orders",
        icon: ShoppingCart,
        route: "/inventory/purchase-orders",
        section: "Inventory",
        permission: "inventory.purchaseOrders.view",
      },
      {
        id: "inv-maintenance",
        label: "Maintenance",
        icon: Wrench,
        route: "/inventory/maintenance",
        section: "Inventory",
        permission: "inventory.maintenance.view",
      },
      {
        id: "inv-assignments",
        label: "Assignments",
        icon: UserCheck,
        route: "/inventory/assignments",
        section: "Inventory",
        permission: "inventory.assets.assign",
      },
      {
        id: "inv-reports",
        label: "Reports",
        icon: FileSpreadsheet,
        route: "/inventory/reports",
        section: "Inventory",
        permission: "inventory.reports.view",
      },
      {
        id: "inv-settings",
        label: "Settings",
        icon: Settings,
        route: "/inventory/settings",
        section: "Inventory",
        permission: "inventory.settings",
      },
    ],
  },
  {
    title: "Administration",
    items: [
      {
        id: "admin-setup",
        label: "School Setup",
        icon: SlidersHorizontal,
        route: "/setup",
        section: "Administration",
        permission: "admin.setup",
      },
      {
        id: "admin-settings",
        label: "System Settings",
        icon: Settings,
        route: "/settings",
        section: "Administration",
        permission: "admin.settings",
      },
      {
        id: "admin-profile",
        label: "My Profile",
        icon: User,
        route: "/profile",
        section: "Administration",
        permission: "profile.view",
      },
    ],
  },
];

/**
 * Filter navigation items based on user role / permissions
 */
export function getFilteredNavigation(userRole?: string): NavSectionConfig[] {
  const role = userRole?.toUpperCase() || "ADMIN";

  // OWNER, ADMIN, PRINCIPAL, SUPER_ADMIN, VICE_PRINCIPAL have full access
  const isSuperOrAdmin =
    role === "OWNER" ||
    role === "ADMIN" ||
    role === "PRINCIPAL" ||
    role === "SUPER_ADMIN" ||
    role === "VICE_PRINCIPAL";

  if (isSuperOrAdmin) {
    return navigationConfig;
  }

  // Role-specific filtering for Teachers, Staff, etc.
  return navigationConfig
    .map((section) => {
      const filteredItems = section.items.filter((item) => {
        if (role === "TEACHER") {
          // Teachers can access core dashboard, students view, academics view, teacher's own attendance & student attendance, profile, and teacher timetable
          return (
            item.route === "/dashboard" ||
            item.route === "/students" ||
            item.route.startsWith("/academics") ||
            item.route === "/attendance" ||
            item.route === "/attendance/students" ||
            item.route === "/attendance/leave" ||
            item.route === "/timetable" ||
            item.route === "/timetable/classes" ||
            item.route === "/timetable/teachers" ||
            item.route.startsWith("/academic-work") ||
            item.route === "/profile"
          );
        }
        if (role === "STAFF") {
          return (
            item.route === "/dashboard" ||
            item.route === "/attendance/leave" ||
            item.route === "/profile"
          );
        }
        return true;
      });

      return {
        ...section,
        items: filteredItems,
      };
    })
    .filter((section) => section.items.length > 0);
}
