/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AcademicsIndexRouteImport } from './routes/academics/index'
import { Route as AcademicsAssignmentsRouteImport } from './routes/academics/assignments'
import { Route as AcademicsSettingsRouteImport } from './routes/academics/settings'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions/index'
import { Route as AdmissionsCounsellingRouteImport } from './routes/admissions/counselling'
import { Route as AdmissionsDocumentsRouteImport } from './routes/admissions/documents'
import { Route as AdmissionsFollowUpsRouteImport } from './routes/admissions/follow-ups'
import { Route as AdmissionsSettingsRouteImport } from './routes/admissions/settings'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as AttendanceLeaveRouteImport } from './routes/attendance/leave'
import { Route as AttendanceReportsRouteImport } from './routes/attendance/reports'
import { Route as AttendanceSettingsRouteImport } from './routes/attendance/settings'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as ParentsParentIdRouteImport } from './routes/parents/$parentId'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students/$studentId'
import { Route as StudentsNewRouteImport } from './routes/students/new'
import { Route as StudentsPromotionsRouteImport } from './routes/students/promotions'
import { Route as TimetableIndexRouteImport } from './routes/timetable/index'
import { Route as TimetableCreateRouteImport } from './routes/timetable/create'
import { Route as TimetablePeriodsRouteImport } from './routes/timetable/periods'
import { Route as TimetableSettingsRouteImport } from './routes/timetable/settings'
import { Route as TimetableSubstitutionsRouteImport } from './routes/timetable/substitutions'
import { Route as AcademicsClassesIndexRouteImport } from './routes/academics/classes/index'
import { Route as AcademicsClassesClassIdRouteImport } from './routes/academics/classes/$classId'
import { Route as AcademicsClassesNewRouteImport } from './routes/academics/classes/new'
import { Route as AcademicsSectionsIndexRouteImport } from './routes/academics/sections/index'
import { Route as AcademicsSectionsSectionIdRouteImport } from './routes/academics/sections/$sectionId'
import { Route as AcademicsSectionsNewRouteImport } from './routes/academics/sections/new'
import { Route as AcademicsSessionsIndexRouteImport } from './routes/academics/sessions/index'
import { Route as AcademicsSessionsSessionIdRouteImport } from './routes/academics/sessions/$sessionId'
import { Route as AcademicsSessionsNewRouteImport } from './routes/academics/sessions/new'
import { Route as AcademicsSubjectsIndexRouteImport } from './routes/academics/subjects/index'
import { Route as AcademicsSubjectsSubjectIdRouteImport } from './routes/academics/subjects/$subjectId'
import { Route as AcademicsSubjectsNewRouteImport } from './routes/academics/subjects/new'
import { Route as AcademicsTeachersIndexRouteImport } from './routes/academics/teachers/index'
import { Route as AcademicsTeachersTeacherIdRouteImport } from './routes/academics/teachers/$teacherId'
import { Route as AcademicsTeachersNewRouteImport } from './routes/academics/teachers/new'
import { Route as AdmissionsAdmittedIndexRouteImport } from './routes/admissions/admitted/index'
import { Route as AdmissionsAdmittedAdmissionIdRouteImport } from './routes/admissions/admitted/$admissionId'
import { Route as AdmissionsApplicationsIndexRouteImport } from './routes/admissions/applications/index'
import { Route as AdmissionsApplicationsApplicationIdRouteImport } from './routes/admissions/applications/$applicationId'
import { Route as AdmissionsApplicationsNewRouteImport } from './routes/admissions/applications/new'
import { Route as AdmissionsEnquiriesIndexRouteImport } from './routes/admissions/enquiries/index'
import { Route as AdmissionsEnquiriesEnquiryIdRouteImport } from './routes/admissions/enquiries/$enquiryId'
import { Route as AdmissionsEnquiriesNewRouteImport } from './routes/admissions/enquiries/new'
import { Route as AttendanceStaffIndexRouteImport } from './routes/attendance/staff/index'
import { Route as AttendanceStaffTakeRouteImport } from './routes/attendance/staff/take'
import { Route as AttendanceStudentsIndexRouteImport } from './routes/attendance/students/index'
import { Route as AttendanceStudentsDateRouteImport } from './routes/attendance/students/$date'
import { Route as AttendanceStudentsTakeRouteImport } from './routes/attendance/students/take'
import { Route as StudentsStudentIdEditRouteImport } from './routes/students/$studentId.edit'
import { Route as TimetableClassesIndexRouteImport } from './routes/timetable/classes/index'
import { Route as TimetableClassesClassIdRouteImport } from './routes/timetable/classes/$classId'
import { Route as TimetableRoomsIndexRouteImport } from './routes/timetable/rooms/index'
import { Route as TimetableTeachersIndexRouteImport } from './routes/timetable/teachers/index'
import { Route as TimetableTeachersTeacherIdRouteImport } from './routes/timetable/teachers/$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/academics/',
  path: '/academics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsAssignmentsRoute = AcademicsAssignmentsRouteImport.update({
  id: '/academics/assignments',
  path: '/academics/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSettingsRoute = AcademicsSettingsRouteImport.update({
  id: '/academics/settings',
  path: '/academics/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsCounsellingRoute = AdmissionsCounsellingRouteImport.update({
  id: '/admissions/counselling',
  path: '/admissions/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsDocumentsRoute = AdmissionsDocumentsRouteImport.update({
  id: '/admissions/documents',
  path: '/admissions/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsFollowUpsRoute = AdmissionsFollowUpsRouteImport.update({
  id: '/admissions/follow-ups',
  path: '/admissions/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsSettingsRoute = AdmissionsSettingsRouteImport.update({
  id: '/admissions/settings',
  path: '/admissions/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceLeaveRoute = AttendanceLeaveRouteImport.update({
  id: '/attendance/leave',
  path: '/attendance/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceReportsRoute = AttendanceReportsRouteImport.update({
  id: '/attendance/reports',
  path: '/attendance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceSettingsRoute = AttendanceSettingsRouteImport.update({
  id: '/attendance/settings',
  path: '/attendance/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentIdRoute = ParentsParentIdRouteImport.update({
  id: '/parents/$parentId',
  path: '/parents/$parentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsPromotionsRoute = StudentsPromotionsRouteImport.update({
  id: '/students/promotions',
  path: '/students/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableIndexRoute = TimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableCreateRoute = TimetableCreateRouteImport.update({
  id: '/timetable/create',
  path: '/timetable/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetablePeriodsRoute = TimetablePeriodsRouteImport.update({
  id: '/timetable/periods',
  path: '/timetable/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableSettingsRoute = TimetableSettingsRouteImport.update({
  id: '/timetable/settings',
  path: '/timetable/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableSubstitutionsRoute = TimetableSubstitutionsRouteImport.update({
  id: '/timetable/substitutions',
  path: '/timetable/substitutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsClassesIndexRoute = AcademicsClassesIndexRouteImport.update({
  id: '/academics/classes/',
  path: '/academics/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsClassesClassIdRoute = AcademicsClassesClassIdRouteImport.update({
  id: '/academics/classes/$classId',
  path: '/academics/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsClassesNewRoute = AcademicsClassesNewRouteImport.update({
  id: '/academics/classes/new',
  path: '/academics/classes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSectionsIndexRoute = AcademicsSectionsIndexRouteImport.update({
  id: '/academics/sections/',
  path: '/academics/sections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSectionsSectionIdRoute =
  AcademicsSectionsSectionIdRouteImport.update({
    id: '/academics/sections/$sectionId',
    path: '/academics/sections/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsSectionsNewRoute = AcademicsSectionsNewRouteImport.update({
  id: '/academics/sections/new',
  path: '/academics/sections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSessionsIndexRoute = AcademicsSessionsIndexRouteImport.update({
  id: '/academics/sessions/',
  path: '/academics/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSessionsSessionIdRoute =
  AcademicsSessionsSessionIdRouteImport.update({
    id: '/academics/sessions/$sessionId',
    path: '/academics/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsSessionsNewRoute = AcademicsSessionsNewRouteImport.update({
  id: '/academics/sessions/new',
  path: '/academics/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSubjectsIndexRoute = AcademicsSubjectsIndexRouteImport.update({
  id: '/academics/subjects/',
  path: '/academics/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSubjectsSubjectIdRoute =
  AcademicsSubjectsSubjectIdRouteImport.update({
    id: '/academics/subjects/$subjectId',
    path: '/academics/subjects/$subjectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsSubjectsNewRoute = AcademicsSubjectsNewRouteImport.update({
  id: '/academics/subjects/new',
  path: '/academics/subjects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsTeachersIndexRoute = AcademicsTeachersIndexRouteImport.update({
  id: '/academics/teachers/',
  path: '/academics/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsTeachersTeacherIdRoute =
  AcademicsTeachersTeacherIdRouteImport.update({
    id: '/academics/teachers/$teacherId',
    path: '/academics/teachers/$teacherId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsTeachersNewRoute = AcademicsTeachersNewRouteImport.update({
  id: '/academics/teachers/new',
  path: '/academics/teachers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAdmittedIndexRoute = AdmissionsAdmittedIndexRouteImport.update({
  id: '/admissions/admitted/',
  path: '/admissions/admitted/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAdmittedAdmissionIdRoute =
  AdmissionsAdmittedAdmissionIdRouteImport.update({
    id: '/admissions/admitted/$admissionId',
    path: '/admissions/admitted/$admissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsIndexRoute =
  AdmissionsApplicationsIndexRouteImport.update({
    id: '/admissions/applications/',
    path: '/admissions/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsApplicationIdRoute =
  AdmissionsApplicationsApplicationIdRouteImport.update({
    id: '/admissions/applications/$applicationId',
    path: '/admissions/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsNewRoute =
  AdmissionsApplicationsNewRouteImport.update({
    id: '/admissions/applications/new',
    path: '/admissions/applications/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesIndexRoute =
  AdmissionsEnquiriesIndexRouteImport.update({
    id: '/admissions/enquiries/',
    path: '/admissions/enquiries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesEnquiryIdRoute =
  AdmissionsEnquiriesEnquiryIdRouteImport.update({
    id: '/admissions/enquiries/$enquiryId',
    path: '/admissions/enquiries/$enquiryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesNewRoute = AdmissionsEnquiriesNewRouteImport.update({
  id: '/admissions/enquiries/new',
  path: '/admissions/enquiries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceStaffIndexRoute = AttendanceStaffIndexRouteImport.update({
  id: '/attendance/staff/',
  path: '/attendance/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceStaffTakeRoute = AttendanceStaffTakeRouteImport.update({
  id: '/attendance/staff/take',
  path: '/attendance/staff/take',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceStudentsIndexRoute = AttendanceStudentsIndexRouteImport.update({
  id: '/attendance/students/',
  path: '/attendance/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceStudentsDateRoute = AttendanceStudentsDateRouteImport.update({
  id: '/attendance/students/$date',
  path: '/attendance/students/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceStudentsTakeRoute = AttendanceStudentsTakeRouteImport.update({
  id: '/attendance/students/take',
  path: '/attendance/students/take',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdEditRoute = StudentsStudentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudentsStudentIdRoute,
} as any)
const TimetableClassesIndexRoute = TimetableClassesIndexRouteImport.update({
  id: '/timetable/classes/',
  path: '/timetable/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableClassesClassIdRoute = TimetableClassesClassIdRouteImport.update({
  id: '/timetable/classes/$classId',
  path: '/timetable/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoomsIndexRoute = TimetableRoomsIndexRouteImport.update({
  id: '/timetable/rooms/',
  path: '/timetable/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableTeachersIndexRoute = TimetableTeachersIndexRouteImport.update({
  id: '/timetable/teachers/',
  path: '/timetable/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableTeachersTeacherIdRoute =
  TimetableTeachersTeacherIdRouteImport.update({
    id: '/timetable/teachers/$teacherId',
    path: '/timetable/teachers/$teacherId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/academics/assignments': typeof AcademicsAssignmentsRoute
  '/academics/settings': typeof AcademicsSettingsRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/timetable/create': typeof TimetableCreateRoute
  '/timetable/periods': typeof TimetablePeriodsRoute
  '/timetable/settings': typeof TimetableSettingsRoute
  '/timetable/substitutions': typeof TimetableSubstitutionsRoute
  '/academics/': typeof AcademicsIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/timetable/': typeof TimetableIndexRoute
  '/academics/classes/$classId': typeof AcademicsClassesClassIdRoute
  '/academics/classes/new': typeof AcademicsClassesNewRoute
  '/academics/sections/$sectionId': typeof AcademicsSectionsSectionIdRoute
  '/academics/sections/new': typeof AcademicsSectionsNewRoute
  '/academics/sessions/$sessionId': typeof AcademicsSessionsSessionIdRoute
  '/academics/sessions/new': typeof AcademicsSessionsNewRoute
  '/academics/subjects/$subjectId': typeof AcademicsSubjectsSubjectIdRoute
  '/academics/subjects/new': typeof AcademicsSubjectsNewRoute
  '/academics/teachers/$teacherId': typeof AcademicsTeachersTeacherIdRoute
  '/academics/teachers/new': typeof AcademicsTeachersNewRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/attendance/staff/take': typeof AttendanceStaffTakeRoute
  '/attendance/students/$date': typeof AttendanceStudentsDateRoute
  '/attendance/students/take': typeof AttendanceStudentsTakeRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/timetable/classes/$classId': typeof TimetableClassesClassIdRoute
  '/timetable/teachers/$teacherId': typeof TimetableTeachersTeacherIdRoute
  '/academics/classes/': typeof AcademicsClassesIndexRoute
  '/academics/sections/': typeof AcademicsSectionsIndexRoute
  '/academics/sessions/': typeof AcademicsSessionsIndexRoute
  '/academics/subjects/': typeof AcademicsSubjectsIndexRoute
  '/academics/teachers/': typeof AcademicsTeachersIndexRoute
  '/admissions/admitted/': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications/': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries/': typeof AdmissionsEnquiriesIndexRoute
  '/attendance/staff/': typeof AttendanceStaffIndexRoute
  '/attendance/students/': typeof AttendanceStudentsIndexRoute
  '/timetable/classes/': typeof TimetableClassesIndexRoute
  '/timetable/rooms/': typeof TimetableRoomsIndexRoute
  '/timetable/teachers/': typeof TimetableTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/academics/assignments': typeof AcademicsAssignmentsRoute
  '/academics/settings': typeof AcademicsSettingsRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/timetable/create': typeof TimetableCreateRoute
  '/timetable/periods': typeof TimetablePeriodsRoute
  '/timetable/settings': typeof TimetableSettingsRoute
  '/timetable/substitutions': typeof TimetableSubstitutionsRoute
  '/academics': typeof AcademicsIndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/timetable': typeof TimetableIndexRoute
  '/academics/classes/$classId': typeof AcademicsClassesClassIdRoute
  '/academics/classes/new': typeof AcademicsClassesNewRoute
  '/academics/sections/$sectionId': typeof AcademicsSectionsSectionIdRoute
  '/academics/sections/new': typeof AcademicsSectionsNewRoute
  '/academics/sessions/$sessionId': typeof AcademicsSessionsSessionIdRoute
  '/academics/sessions/new': typeof AcademicsSessionsNewRoute
  '/academics/subjects/$subjectId': typeof AcademicsSubjectsSubjectIdRoute
  '/academics/subjects/new': typeof AcademicsSubjectsNewRoute
  '/academics/teachers/$teacherId': typeof AcademicsTeachersTeacherIdRoute
  '/academics/teachers/new': typeof AcademicsTeachersNewRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/attendance/staff/take': typeof AttendanceStaffTakeRoute
  '/attendance/students/$date': typeof AttendanceStudentsDateRoute
  '/attendance/students/take': typeof AttendanceStudentsTakeRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/timetable/classes/$classId': typeof TimetableClassesClassIdRoute
  '/timetable/teachers/$teacherId': typeof TimetableTeachersTeacherIdRoute
  '/academics/classes': typeof AcademicsClassesIndexRoute
  '/academics/sections': typeof AcademicsSectionsIndexRoute
  '/academics/sessions': typeof AcademicsSessionsIndexRoute
  '/academics/subjects': typeof AcademicsSubjectsIndexRoute
  '/academics/teachers': typeof AcademicsTeachersIndexRoute
  '/admissions/admitted': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesIndexRoute
  '/attendance/staff': typeof AttendanceStaffIndexRoute
  '/attendance/students': typeof AttendanceStudentsIndexRoute
  '/timetable/classes': typeof TimetableClassesIndexRoute
  '/timetable/rooms': typeof TimetableRoomsIndexRoute
  '/timetable/teachers': typeof TimetableTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/academics/assignments': typeof AcademicsAssignmentsRoute
  '/academics/settings': typeof AcademicsSettingsRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/attendance/leave': typeof AttendanceLeaveRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/timetable/create': typeof TimetableCreateRoute
  '/timetable/periods': typeof TimetablePeriodsRoute
  '/timetable/settings': typeof TimetableSettingsRoute
  '/timetable/substitutions': typeof TimetableSubstitutionsRoute
  '/academics/': typeof AcademicsIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/timetable/': typeof TimetableIndexRoute
  '/academics/classes/$classId': typeof AcademicsClassesClassIdRoute
  '/academics/classes/new': typeof AcademicsClassesNewRoute
  '/academics/sections/$sectionId': typeof AcademicsSectionsSectionIdRoute
  '/academics/sections/new': typeof AcademicsSectionsNewRoute
  '/academics/sessions/$sessionId': typeof AcademicsSessionsSessionIdRoute
  '/academics/sessions/new': typeof AcademicsSessionsNewRoute
  '/academics/subjects/$subjectId': typeof AcademicsSubjectsSubjectIdRoute
  '/academics/subjects/new': typeof AcademicsSubjectsNewRoute
  '/academics/teachers/$teacherId': typeof AcademicsTeachersTeacherIdRoute
  '/academics/teachers/new': typeof AcademicsTeachersNewRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/attendance/staff/take': typeof AttendanceStaffTakeRoute
  '/attendance/students/$date': typeof AttendanceStudentsDateRoute
  '/attendance/students/take': typeof AttendanceStudentsTakeRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/timetable/classes/$classId': typeof TimetableClassesClassIdRoute
  '/timetable/teachers/$teacherId': typeof TimetableTeachersTeacherIdRoute
  '/academics/classes/': typeof AcademicsClassesIndexRoute
  '/academics/sections/': typeof AcademicsSectionsIndexRoute
  '/academics/sessions/': typeof AcademicsSessionsIndexRoute
  '/academics/subjects/': typeof AcademicsSubjectsIndexRoute
  '/academics/teachers/': typeof AcademicsTeachersIndexRoute
  '/admissions/admitted/': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications/': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries/': typeof AdmissionsEnquiriesIndexRoute
  '/attendance/staff/': typeof AttendanceStaffIndexRoute
  '/attendance/students/': typeof AttendanceStudentsIndexRoute
  '/timetable/classes/': typeof TimetableClassesIndexRoute
  '/timetable/rooms/': typeof TimetableRoomsIndexRoute
  '/timetable/teachers/': typeof TimetableTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/academics/assignments'
    | '/academics/settings'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/attendance/leave'
    | '/attendance/reports'
    | '/attendance/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/timetable/create'
    | '/timetable/periods'
    | '/timetable/settings'
    | '/timetable/substitutions'
    | '/academics/'
    | '/admissions/'
    | '/attendance/'
    | '/parents/'
    | '/students/'
    | '/timetable/'
    | '/academics/classes/$classId'
    | '/academics/classes/new'
    | '/academics/sections/$sectionId'
    | '/academics/sections/new'
    | '/academics/sessions/$sessionId'
    | '/academics/sessions/new'
    | '/academics/subjects/$subjectId'
    | '/academics/subjects/new'
    | '/academics/teachers/$teacherId'
    | '/academics/teachers/new'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/attendance/staff/take'
    | '/attendance/students/$date'
    | '/attendance/students/take'
    | '/students/$studentId/edit'
    | '/timetable/classes/$classId'
    | '/timetable/teachers/$teacherId'
    | '/academics/classes/'
    | '/academics/sections/'
    | '/academics/sessions/'
    | '/academics/subjects/'
    | '/academics/teachers/'
    | '/admissions/admitted/'
    | '/admissions/applications/'
    | '/admissions/enquiries/'
    | '/attendance/staff/'
    | '/attendance/students/'
    | '/timetable/classes/'
    | '/timetable/rooms/'
    | '/timetable/teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/academics/assignments'
    | '/academics/settings'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/attendance/leave'
    | '/attendance/reports'
    | '/attendance/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/timetable/create'
    | '/timetable/periods'
    | '/timetable/settings'
    | '/timetable/substitutions'
    | '/academics'
    | '/admissions'
    | '/attendance'
    | '/parents'
    | '/students'
    | '/timetable'
    | '/academics/classes/$classId'
    | '/academics/classes/new'
    | '/academics/sections/$sectionId'
    | '/academics/sections/new'
    | '/academics/sessions/$sessionId'
    | '/academics/sessions/new'
    | '/academics/subjects/$subjectId'
    | '/academics/subjects/new'
    | '/academics/teachers/$teacherId'
    | '/academics/teachers/new'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/attendance/staff/take'
    | '/attendance/students/$date'
    | '/attendance/students/take'
    | '/students/$studentId/edit'
    | '/timetable/classes/$classId'
    | '/timetable/teachers/$teacherId'
    | '/academics/classes'
    | '/academics/sections'
    | '/academics/sessions'
    | '/academics/subjects'
    | '/academics/teachers'
    | '/admissions/admitted'
    | '/admissions/applications'
    | '/admissions/enquiries'
    | '/attendance/staff'
    | '/attendance/students'
    | '/timetable/classes'
    | '/timetable/rooms'
    | '/timetable/teachers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/academics/assignments'
    | '/academics/settings'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/attendance/leave'
    | '/attendance/reports'
    | '/attendance/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/timetable/create'
    | '/timetable/periods'
    | '/timetable/settings'
    | '/timetable/substitutions'
    | '/academics/'
    | '/admissions/'
    | '/attendance/'
    | '/parents/'
    | '/students/'
    | '/timetable/'
    | '/academics/classes/$classId'
    | '/academics/classes/new'
    | '/academics/sections/$sectionId'
    | '/academics/sections/new'
    | '/academics/sessions/$sessionId'
    | '/academics/sessions/new'
    | '/academics/subjects/$subjectId'
    | '/academics/subjects/new'
    | '/academics/teachers/$teacherId'
    | '/academics/teachers/new'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/attendance/staff/take'
    | '/attendance/students/$date'
    | '/attendance/students/take'
    | '/students/$studentId/edit'
    | '/timetable/classes/$classId'
    | '/timetable/teachers/$teacherId'
    | '/academics/classes/'
    | '/academics/sections/'
    | '/academics/sessions/'
    | '/academics/subjects/'
    | '/academics/teachers/'
    | '/admissions/admitted/'
    | '/admissions/applications/'
    | '/admissions/enquiries/'
    | '/attendance/staff/'
    | '/attendance/students/'
    | '/timetable/classes/'
    | '/timetable/rooms/'
    | '/timetable/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  AcademicsAssignmentsRoute: typeof AcademicsAssignmentsRoute
  AcademicsSettingsRoute: typeof AcademicsSettingsRoute
  AdmissionsCounsellingRoute: typeof AdmissionsCounsellingRoute
  AdmissionsDocumentsRoute: typeof AdmissionsDocumentsRoute
  AdmissionsFollowUpsRoute: typeof AdmissionsFollowUpsRoute
  AdmissionsSettingsRoute: typeof AdmissionsSettingsRoute
  AttendanceLeaveRoute: typeof AttendanceLeaveRoute
  AttendanceReportsRoute: typeof AttendanceReportsRoute
  AttendanceSettingsRoute: typeof AttendanceSettingsRoute
  ParentsParentIdRoute: typeof ParentsParentIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRouteWithChildren
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsPromotionsRoute: typeof StudentsPromotionsRoute
  TimetableCreateRoute: typeof TimetableCreateRoute
  TimetablePeriodsRoute: typeof TimetablePeriodsRoute
  TimetableSettingsRoute: typeof TimetableSettingsRoute
  TimetableSubstitutionsRoute: typeof TimetableSubstitutionsRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TimetableIndexRoute: typeof TimetableIndexRoute
  AcademicsClassesClassIdRoute: typeof AcademicsClassesClassIdRoute
  AcademicsClassesNewRoute: typeof AcademicsClassesNewRoute
  AcademicsSectionsSectionIdRoute: typeof AcademicsSectionsSectionIdRoute
  AcademicsSectionsNewRoute: typeof AcademicsSectionsNewRoute
  AcademicsSessionsSessionIdRoute: typeof AcademicsSessionsSessionIdRoute
  AcademicsSessionsNewRoute: typeof AcademicsSessionsNewRoute
  AcademicsSubjectsSubjectIdRoute: typeof AcademicsSubjectsSubjectIdRoute
  AcademicsSubjectsNewRoute: typeof AcademicsSubjectsNewRoute
  AcademicsTeachersTeacherIdRoute: typeof AcademicsTeachersTeacherIdRoute
  AcademicsTeachersNewRoute: typeof AcademicsTeachersNewRoute
  AdmissionsAdmittedAdmissionIdRoute: typeof AdmissionsAdmittedAdmissionIdRoute
  AdmissionsApplicationsApplicationIdRoute: typeof AdmissionsApplicationsApplicationIdRoute
  AdmissionsApplicationsNewRoute: typeof AdmissionsApplicationsNewRoute
  AdmissionsEnquiriesEnquiryIdRoute: typeof AdmissionsEnquiriesEnquiryIdRoute
  AdmissionsEnquiriesNewRoute: typeof AdmissionsEnquiriesNewRoute
  AttendanceStaffTakeRoute: typeof AttendanceStaffTakeRoute
  AttendanceStudentsDateRoute: typeof AttendanceStudentsDateRoute
  AttendanceStudentsTakeRoute: typeof AttendanceStudentsTakeRoute
  TimetableClassesClassIdRoute: typeof TimetableClassesClassIdRoute
  TimetableTeachersTeacherIdRoute: typeof TimetableTeachersTeacherIdRoute
  AcademicsClassesIndexRoute: typeof AcademicsClassesIndexRoute
  AcademicsSectionsIndexRoute: typeof AcademicsSectionsIndexRoute
  AcademicsSessionsIndexRoute: typeof AcademicsSessionsIndexRoute
  AcademicsSubjectsIndexRoute: typeof AcademicsSubjectsIndexRoute
  AcademicsTeachersIndexRoute: typeof AcademicsTeachersIndexRoute
  AdmissionsAdmittedIndexRoute: typeof AdmissionsAdmittedIndexRoute
  AdmissionsApplicationsIndexRoute: typeof AdmissionsApplicationsIndexRoute
  AdmissionsEnquiriesIndexRoute: typeof AdmissionsEnquiriesIndexRoute
  AttendanceStaffIndexRoute: typeof AttendanceStaffIndexRoute
  AttendanceStudentsIndexRoute: typeof AttendanceStudentsIndexRoute
  TimetableClassesIndexRoute: typeof TimetableClassesIndexRoute
  TimetableRoomsIndexRoute: typeof TimetableRoomsIndexRoute
  TimetableTeachersIndexRoute: typeof TimetableTeachersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/': {
      id: '/academics/'
      path: '/academics'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/assignments': {
      id: '/academics/assignments'
      path: '/academics/assignments'
      fullPath: '/academics/assignments'
      preLoaderRoute: typeof AcademicsAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/settings': {
      id: '/academics/settings'
      path: '/academics/settings'
      fullPath: '/academics/settings'
      preLoaderRoute: typeof AcademicsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/counselling': {
      id: '/admissions/counselling'
      path: '/admissions/counselling'
      fullPath: '/admissions/counselling'
      preLoaderRoute: typeof AdmissionsCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/documents': {
      id: '/admissions/documents'
      path: '/admissions/documents'
      fullPath: '/admissions/documents'
      preLoaderRoute: typeof AdmissionsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/follow-ups': {
      id: '/admissions/follow-ups'
      path: '/admissions/follow-ups'
      fullPath: '/admissions/follow-ups'
      preLoaderRoute: typeof AdmissionsFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/settings': {
      id: '/admissions/settings'
      path: '/admissions/settings'
      fullPath: '/admissions/settings'
      preLoaderRoute: typeof AdmissionsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/leave': {
      id: '/attendance/leave'
      path: '/attendance/leave'
      fullPath: '/attendance/leave'
      preLoaderRoute: typeof AttendanceLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/reports': {
      id: '/attendance/reports'
      path: '/attendance/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof AttendanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/settings': {
      id: '/attendance/settings'
      path: '/attendance/settings'
      fullPath: '/attendance/settings'
      preLoaderRoute: typeof AttendanceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/$parentId': {
      id: '/parents/$parentId'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId'
      preLoaderRoute: typeof ParentsParentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/promotions': {
      id: '/students/promotions'
      path: '/students/promotions'
      fullPath: '/students/promotions'
      preLoaderRoute: typeof StudentsPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/': {
      id: '/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof TimetableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/create': {
      id: '/timetable/create'
      path: '/timetable/create'
      fullPath: '/timetable/create'
      preLoaderRoute: typeof TimetableCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/periods': {
      id: '/timetable/periods'
      path: '/timetable/periods'
      fullPath: '/timetable/periods'
      preLoaderRoute: typeof TimetablePeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/settings': {
      id: '/timetable/settings'
      path: '/timetable/settings'
      fullPath: '/timetable/settings'
      preLoaderRoute: typeof TimetableSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/substitutions': {
      id: '/timetable/substitutions'
      path: '/timetable/substitutions'
      fullPath: '/timetable/substitutions'
      preLoaderRoute: typeof TimetableSubstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/classes/': {
      id: '/academics/classes/'
      path: '/academics/classes'
      fullPath: '/academics/classes/'
      preLoaderRoute: typeof AcademicsClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/classes/$classId': {
      id: '/academics/classes/$classId'
      path: '/academics/classes/$classId'
      fullPath: '/academics/classes/$classId'
      preLoaderRoute: typeof AcademicsClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/classes/new': {
      id: '/academics/classes/new'
      path: '/academics/classes/new'
      fullPath: '/academics/classes/new'
      preLoaderRoute: typeof AcademicsClassesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sections/': {
      id: '/academics/sections/'
      path: '/academics/sections'
      fullPath: '/academics/sections/'
      preLoaderRoute: typeof AcademicsSectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sections/$sectionId': {
      id: '/academics/sections/$sectionId'
      path: '/academics/sections/$sectionId'
      fullPath: '/academics/sections/$sectionId'
      preLoaderRoute: typeof AcademicsSectionsSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sections/new': {
      id: '/academics/sections/new'
      path: '/academics/sections/new'
      fullPath: '/academics/sections/new'
      preLoaderRoute: typeof AcademicsSectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sessions/': {
      id: '/academics/sessions/'
      path: '/academics/sessions'
      fullPath: '/academics/sessions/'
      preLoaderRoute: typeof AcademicsSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sessions/$sessionId': {
      id: '/academics/sessions/$sessionId'
      path: '/academics/sessions/$sessionId'
      fullPath: '/academics/sessions/$sessionId'
      preLoaderRoute: typeof AcademicsSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/sessions/new': {
      id: '/academics/sessions/new'
      path: '/academics/sessions/new'
      fullPath: '/academics/sessions/new'
      preLoaderRoute: typeof AcademicsSessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/subjects/': {
      id: '/academics/subjects/'
      path: '/academics/subjects'
      fullPath: '/academics/subjects/'
      preLoaderRoute: typeof AcademicsSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/subjects/$subjectId': {
      id: '/academics/subjects/$subjectId'
      path: '/academics/subjects/$subjectId'
      fullPath: '/academics/subjects/$subjectId'
      preLoaderRoute: typeof AcademicsSubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/subjects/new': {
      id: '/academics/subjects/new'
      path: '/academics/subjects/new'
      fullPath: '/academics/subjects/new'
      preLoaderRoute: typeof AcademicsSubjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/teachers/': {
      id: '/academics/teachers/'
      path: '/academics/teachers'
      fullPath: '/academics/teachers/'
      preLoaderRoute: typeof AcademicsTeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/teachers/$teacherId': {
      id: '/academics/teachers/$teacherId'
      path: '/academics/teachers/$teacherId'
      fullPath: '/academics/teachers/$teacherId'
      preLoaderRoute: typeof AcademicsTeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/teachers/new': {
      id: '/academics/teachers/new'
      path: '/academics/teachers/new'
      fullPath: '/academics/teachers/new'
      preLoaderRoute: typeof AcademicsTeachersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/admitted/': {
      id: '/admissions/admitted/'
      path: '/admissions/admitted'
      fullPath: '/admissions/admitted/'
      preLoaderRoute: typeof AdmissionsAdmittedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/admitted/$admissionId': {
      id: '/admissions/admitted/$admissionId'
      path: '/admissions/admitted/$admissionId'
      fullPath: '/admissions/admitted/$admissionId'
      preLoaderRoute: typeof AdmissionsAdmittedAdmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/': {
      id: '/admissions/applications/'
      path: '/admissions/applications'
      fullPath: '/admissions/applications/'
      preLoaderRoute: typeof AdmissionsApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/$applicationId': {
      id: '/admissions/applications/$applicationId'
      path: '/admissions/applications/$applicationId'
      fullPath: '/admissions/applications/$applicationId'
      preLoaderRoute: typeof AdmissionsApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/new': {
      id: '/admissions/applications/new'
      path: '/admissions/applications/new'
      fullPath: '/admissions/applications/new'
      preLoaderRoute: typeof AdmissionsApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/': {
      id: '/admissions/enquiries/'
      path: '/admissions/enquiries'
      fullPath: '/admissions/enquiries/'
      preLoaderRoute: typeof AdmissionsEnquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/$enquiryId': {
      id: '/admissions/enquiries/$enquiryId'
      path: '/admissions/enquiries/$enquiryId'
      fullPath: '/admissions/enquiries/$enquiryId'
      preLoaderRoute: typeof AdmissionsEnquiriesEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/new': {
      id: '/admissions/enquiries/new'
      path: '/admissions/enquiries/new'
      fullPath: '/admissions/enquiries/new'
      preLoaderRoute: typeof AdmissionsEnquiriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/staff/': {
      id: '/attendance/staff/'
      path: '/attendance/staff'
      fullPath: '/attendance/staff/'
      preLoaderRoute: typeof AttendanceStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/staff/take': {
      id: '/attendance/staff/take'
      path: '/attendance/staff/take'
      fullPath: '/attendance/staff/take'
      preLoaderRoute: typeof AttendanceStaffTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/students/': {
      id: '/attendance/students/'
      path: '/attendance/students'
      fullPath: '/attendance/students/'
      preLoaderRoute: typeof AttendanceStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/students/$date': {
      id: '/attendance/students/$date'
      path: '/attendance/students/$date'
      fullPath: '/attendance/students/$date'
      preLoaderRoute: typeof AttendanceStudentsDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/students/take': {
      id: '/attendance/students/take'
      path: '/attendance/students/take'
      fullPath: '/attendance/students/take'
      preLoaderRoute: typeof AttendanceStudentsTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/edit': {
      id: '/students/$studentId/edit'
      path: '/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof StudentsStudentIdEditRouteImport
      parentRoute: typeof StudentsStudentIdRoute
    }
    '/timetable/classes/': {
      id: '/timetable/classes/'
      path: '/timetable/classes'
      fullPath: '/timetable/classes/'
      preLoaderRoute: typeof TimetableClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/classes/$classId': {
      id: '/timetable/classes/$classId'
      path: '/timetable/classes/$classId'
      fullPath: '/timetable/classes/$classId'
      preLoaderRoute: typeof TimetableClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/rooms/': {
      id: '/timetable/rooms/'
      path: '/timetable/rooms'
      fullPath: '/timetable/rooms/'
      preLoaderRoute: typeof TimetableRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/teachers/': {
      id: '/timetable/teachers/'
      path: '/timetable/teachers'
      fullPath: '/timetable/teachers/'
      preLoaderRoute: typeof TimetableTeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/teachers/$teacherId': {
      id: '/timetable/teachers/$teacherId'
      path: '/timetable/teachers/$teacherId'
      fullPath: '/timetable/teachers/$teacherId'
      preLoaderRoute: typeof TimetableTeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentsStudentIdRouteChildren {
  StudentsStudentIdEditRoute: typeof StudentsStudentIdEditRoute
}

const StudentsStudentIdRouteChildren: StudentsStudentIdRouteChildren = {
  StudentsStudentIdEditRoute: StudentsStudentIdEditRoute,
}

const StudentsStudentIdRouteWithChildren =
  StudentsStudentIdRoute._addFileChildren(StudentsStudentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  AcademicsAssignmentsRoute: AcademicsAssignmentsRoute,
  AcademicsSettingsRoute: AcademicsSettingsRoute,
  AdmissionsCounsellingRoute: AdmissionsCounsellingRoute,
  AdmissionsDocumentsRoute: AdmissionsDocumentsRoute,
  AdmissionsFollowUpsRoute: AdmissionsFollowUpsRoute,
  AdmissionsSettingsRoute: AdmissionsSettingsRoute,
  AttendanceLeaveRoute: AttendanceLeaveRoute,
  AttendanceReportsRoute: AttendanceReportsRoute,
  AttendanceSettingsRoute: AttendanceSettingsRoute,
  ParentsParentIdRoute: ParentsParentIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRouteWithChildren,
  StudentsNewRoute: StudentsNewRoute,
  StudentsPromotionsRoute: StudentsPromotionsRoute,
  TimetableCreateRoute: TimetableCreateRoute,
  TimetablePeriodsRoute: TimetablePeriodsRoute,
  TimetableSettingsRoute: TimetableSettingsRoute,
  TimetableSubstitutionsRoute: TimetableSubstitutionsRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TimetableIndexRoute: TimetableIndexRoute,
  AcademicsClassesClassIdRoute: AcademicsClassesClassIdRoute,
  AcademicsClassesNewRoute: AcademicsClassesNewRoute,
  AcademicsSectionsSectionIdRoute: AcademicsSectionsSectionIdRoute,
  AcademicsSectionsNewRoute: AcademicsSectionsNewRoute,
  AcademicsSessionsSessionIdRoute: AcademicsSessionsSessionIdRoute,
  AcademicsSessionsNewRoute: AcademicsSessionsNewRoute,
  AcademicsSubjectsSubjectIdRoute: AcademicsSubjectsSubjectIdRoute,
  AcademicsSubjectsNewRoute: AcademicsSubjectsNewRoute,
  AcademicsTeachersTeacherIdRoute: AcademicsTeachersTeacherIdRoute,
  AcademicsTeachersNewRoute: AcademicsTeachersNewRoute,
  AdmissionsAdmittedAdmissionIdRoute: AdmissionsAdmittedAdmissionIdRoute,
  AdmissionsApplicationsApplicationIdRoute:
    AdmissionsApplicationsApplicationIdRoute,
  AdmissionsApplicationsNewRoute: AdmissionsApplicationsNewRoute,
  AdmissionsEnquiriesEnquiryIdRoute: AdmissionsEnquiriesEnquiryIdRoute,
  AdmissionsEnquiriesNewRoute: AdmissionsEnquiriesNewRoute,
  AttendanceStaffTakeRoute: AttendanceStaffTakeRoute,
  AttendanceStudentsDateRoute: AttendanceStudentsDateRoute,
  AttendanceStudentsTakeRoute: AttendanceStudentsTakeRoute,
  TimetableClassesClassIdRoute: TimetableClassesClassIdRoute,
  TimetableTeachersTeacherIdRoute: TimetableTeachersTeacherIdRoute,
  AcademicsClassesIndexRoute: AcademicsClassesIndexRoute,
  AcademicsSectionsIndexRoute: AcademicsSectionsIndexRoute,
  AcademicsSessionsIndexRoute: AcademicsSessionsIndexRoute,
  AcademicsSubjectsIndexRoute: AcademicsSubjectsIndexRoute,
  AcademicsTeachersIndexRoute: AcademicsTeachersIndexRoute,
  AdmissionsAdmittedIndexRoute: AdmissionsAdmittedIndexRoute,
  AdmissionsApplicationsIndexRoute: AdmissionsApplicationsIndexRoute,
  AdmissionsEnquiriesIndexRoute: AdmissionsEnquiriesIndexRoute,
  AttendanceStaffIndexRoute: AttendanceStaffIndexRoute,
  AttendanceStudentsIndexRoute: AttendanceStudentsIndexRoute,
  TimetableClassesIndexRoute: TimetableClassesIndexRoute,
  TimetableRoomsIndexRoute: TimetableRoomsIndexRoute,
  TimetableTeachersIndexRoute: TimetableTeachersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
