/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions/index'
import { Route as AdmissionsCounsellingRouteImport } from './routes/admissions/counselling'
import { Route as AdmissionsDocumentsRouteImport } from './routes/admissions/documents'
import { Route as AdmissionsFollowUpsRouteImport } from './routes/admissions/follow-ups'
import { Route as AdmissionsSettingsRouteImport } from './routes/admissions/settings'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as ParentsParentIdRouteImport } from './routes/parents/$parentId'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students/$studentId'
import { Route as StudentsNewRouteImport } from './routes/students/new'
import { Route as StudentsPromotionsRouteImport } from './routes/students/promotions'
import { Route as AdmissionsAdmittedIndexRouteImport } from './routes/admissions/admitted/index'
import { Route as AdmissionsAdmittedAdmissionIdRouteImport } from './routes/admissions/admitted/$admissionId'
import { Route as AdmissionsApplicationsIndexRouteImport } from './routes/admissions/applications/index'
import { Route as AdmissionsApplicationsApplicationIdRouteImport } from './routes/admissions/applications/$applicationId'
import { Route as AdmissionsApplicationsNewRouteImport } from './routes/admissions/applications/new'
import { Route as AdmissionsEnquiriesIndexRouteImport } from './routes/admissions/enquiries/index'
import { Route as AdmissionsEnquiriesEnquiryIdRouteImport } from './routes/admissions/enquiries/$enquiryId'
import { Route as AdmissionsEnquiriesNewRouteImport } from './routes/admissions/enquiries/new'
import { Route as StudentsStudentIdEditRouteImport } from './routes/students/$studentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsCounsellingRoute = AdmissionsCounsellingRouteImport.update({
  id: '/admissions/counselling',
  path: '/admissions/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsDocumentsRoute = AdmissionsDocumentsRouteImport.update({
  id: '/admissions/documents',
  path: '/admissions/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsFollowUpsRoute = AdmissionsFollowUpsRouteImport.update({
  id: '/admissions/follow-ups',
  path: '/admissions/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsSettingsRoute = AdmissionsSettingsRouteImport.update({
  id: '/admissions/settings',
  path: '/admissions/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentIdRoute = ParentsParentIdRouteImport.update({
  id: '/parents/$parentId',
  path: '/parents/$parentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsPromotionsRoute = StudentsPromotionsRouteImport.update({
  id: '/students/promotions',
  path: '/students/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAdmittedIndexRoute = AdmissionsAdmittedIndexRouteImport.update({
  id: '/admissions/admitted/',
  path: '/admissions/admitted/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAdmittedAdmissionIdRoute =
  AdmissionsAdmittedAdmissionIdRouteImport.update({
    id: '/admissions/admitted/$admissionId',
    path: '/admissions/admitted/$admissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsIndexRoute =
  AdmissionsApplicationsIndexRouteImport.update({
    id: '/admissions/applications/',
    path: '/admissions/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsApplicationIdRoute =
  AdmissionsApplicationsApplicationIdRouteImport.update({
    id: '/admissions/applications/$applicationId',
    path: '/admissions/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsApplicationsNewRoute =
  AdmissionsApplicationsNewRouteImport.update({
    id: '/admissions/applications/new',
    path: '/admissions/applications/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesIndexRoute =
  AdmissionsEnquiriesIndexRouteImport.update({
    id: '/admissions/enquiries/',
    path: '/admissions/enquiries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesEnquiryIdRoute =
  AdmissionsEnquiriesEnquiryIdRouteImport.update({
    id: '/admissions/enquiries/$enquiryId',
    path: '/admissions/enquiries/$enquiryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsEnquiriesNewRoute = AdmissionsEnquiriesNewRouteImport.update({
  id: '/admissions/enquiries/new',
  path: '/admissions/enquiries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdEditRoute = StudentsStudentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudentsStudentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/admissions/admitted/': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications/': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries/': typeof AdmissionsEnquiriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/admissions/admitted': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/admissions/counselling': typeof AdmissionsCounsellingRoute
  '/admissions/documents': typeof AdmissionsDocumentsRoute
  '/admissions/follow-ups': typeof AdmissionsFollowUpsRoute
  '/admissions/settings': typeof AdmissionsSettingsRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/promotions': typeof StudentsPromotionsRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/admissions/admitted/$admissionId': typeof AdmissionsAdmittedAdmissionIdRoute
  '/admissions/applications/$applicationId': typeof AdmissionsApplicationsApplicationIdRoute
  '/admissions/applications/new': typeof AdmissionsApplicationsNewRoute
  '/admissions/enquiries/$enquiryId': typeof AdmissionsEnquiriesEnquiryIdRoute
  '/admissions/enquiries/new': typeof AdmissionsEnquiriesNewRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/admissions/admitted/': typeof AdmissionsAdmittedIndexRoute
  '/admissions/applications/': typeof AdmissionsApplicationsIndexRoute
  '/admissions/enquiries/': typeof AdmissionsEnquiriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/admissions/'
    | '/parents/'
    | '/students/'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/students/$studentId/edit'
    | '/admissions/admitted/'
    | '/admissions/applications/'
    | '/admissions/enquiries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/admissions'
    | '/parents'
    | '/students'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/students/$studentId/edit'
    | '/admissions/admitted'
    | '/admissions/applications'
    | '/admissions/enquiries'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/admissions/counselling'
    | '/admissions/documents'
    | '/admissions/follow-ups'
    | '/admissions/settings'
    | '/parents/$parentId'
    | '/students/$studentId'
    | '/students/new'
    | '/students/promotions'
    | '/admissions/'
    | '/parents/'
    | '/students/'
    | '/admissions/admitted/$admissionId'
    | '/admissions/applications/$applicationId'
    | '/admissions/applications/new'
    | '/admissions/enquiries/$enquiryId'
    | '/admissions/enquiries/new'
    | '/students/$studentId/edit'
    | '/admissions/admitted/'
    | '/admissions/applications/'
    | '/admissions/enquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  AdmissionsCounsellingRoute: typeof AdmissionsCounsellingRoute
  AdmissionsDocumentsRoute: typeof AdmissionsDocumentsRoute
  AdmissionsFollowUpsRoute: typeof AdmissionsFollowUpsRoute
  AdmissionsSettingsRoute: typeof AdmissionsSettingsRoute
  ParentsParentIdRoute: typeof ParentsParentIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRouteWithChildren
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsPromotionsRoute: typeof StudentsPromotionsRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  AdmissionsAdmittedAdmissionIdRoute: typeof AdmissionsAdmittedAdmissionIdRoute
  AdmissionsApplicationsApplicationIdRoute: typeof AdmissionsApplicationsApplicationIdRoute
  AdmissionsApplicationsNewRoute: typeof AdmissionsApplicationsNewRoute
  AdmissionsEnquiriesEnquiryIdRoute: typeof AdmissionsEnquiriesEnquiryIdRoute
  AdmissionsEnquiriesNewRoute: typeof AdmissionsEnquiriesNewRoute
  AdmissionsAdmittedIndexRoute: typeof AdmissionsAdmittedIndexRoute
  AdmissionsApplicationsIndexRoute: typeof AdmissionsApplicationsIndexRoute
  AdmissionsEnquiriesIndexRoute: typeof AdmissionsEnquiriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/counselling': {
      id: '/admissions/counselling'
      path: '/admissions/counselling'
      fullPath: '/admissions/counselling'
      preLoaderRoute: typeof AdmissionsCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/documents': {
      id: '/admissions/documents'
      path: '/admissions/documents'
      fullPath: '/admissions/documents'
      preLoaderRoute: typeof AdmissionsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/follow-ups': {
      id: '/admissions/follow-ups'
      path: '/admissions/follow-ups'
      fullPath: '/admissions/follow-ups'
      preLoaderRoute: typeof AdmissionsFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/settings': {
      id: '/admissions/settings'
      path: '/admissions/settings'
      fullPath: '/admissions/settings'
      preLoaderRoute: typeof AdmissionsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/$parentId': {
      id: '/parents/$parentId'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId'
      preLoaderRoute: typeof ParentsParentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/promotions': {
      id: '/students/promotions'
      path: '/students/promotions'
      fullPath: '/students/promotions'
      preLoaderRoute: typeof StudentsPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/admitted/': {
      id: '/admissions/admitted/'
      path: '/admissions/admitted'
      fullPath: '/admissions/admitted/'
      preLoaderRoute: typeof AdmissionsAdmittedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/admitted/$admissionId': {
      id: '/admissions/admitted/$admissionId'
      path: '/admissions/admitted/$admissionId'
      fullPath: '/admissions/admitted/$admissionId'
      preLoaderRoute: typeof AdmissionsAdmittedAdmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/': {
      id: '/admissions/applications/'
      path: '/admissions/applications'
      fullPath: '/admissions/applications/'
      preLoaderRoute: typeof AdmissionsApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/$applicationId': {
      id: '/admissions/applications/$applicationId'
      path: '/admissions/applications/$applicationId'
      fullPath: '/admissions/applications/$applicationId'
      preLoaderRoute: typeof AdmissionsApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications/new': {
      id: '/admissions/applications/new'
      path: '/admissions/applications/new'
      fullPath: '/admissions/applications/new'
      preLoaderRoute: typeof AdmissionsApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/': {
      id: '/admissions/enquiries/'
      path: '/admissions/enquiries'
      fullPath: '/admissions/enquiries/'
      preLoaderRoute: typeof AdmissionsEnquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/$enquiryId': {
      id: '/admissions/enquiries/$enquiryId'
      path: '/admissions/enquiries/$enquiryId'
      fullPath: '/admissions/enquiries/$enquiryId'
      preLoaderRoute: typeof AdmissionsEnquiriesEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries/new': {
      id: '/admissions/enquiries/new'
      path: '/admissions/enquiries/new'
      fullPath: '/admissions/enquiries/new'
      preLoaderRoute: typeof AdmissionsEnquiriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/edit': {
      id: '/students/$studentId/edit'
      path: '/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof StudentsStudentIdEditRouteImport
      parentRoute: typeof StudentsStudentIdRoute
    }
  }
}

interface StudentsStudentIdRouteChildren {
  StudentsStudentIdEditRoute: typeof StudentsStudentIdEditRoute
}

const StudentsStudentIdRouteChildren: StudentsStudentIdRouteChildren = {
  StudentsStudentIdEditRoute: StudentsStudentIdEditRoute,
}

const StudentsStudentIdRouteWithChildren =
  StudentsStudentIdRoute._addFileChildren(StudentsStudentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  AdmissionsCounsellingRoute: AdmissionsCounsellingRoute,
  AdmissionsDocumentsRoute: AdmissionsDocumentsRoute,
  AdmissionsFollowUpsRoute: AdmissionsFollowUpsRoute,
  AdmissionsSettingsRoute: AdmissionsSettingsRoute,
  ParentsParentIdRoute: ParentsParentIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRouteWithChildren,
  StudentsNewRoute: StudentsNewRoute,
  StudentsPromotionsRoute: StudentsPromotionsRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  AdmissionsAdmittedAdmissionIdRoute: AdmissionsAdmittedAdmissionIdRoute,
  AdmissionsApplicationsApplicationIdRoute:
    AdmissionsApplicationsApplicationIdRoute,
  AdmissionsApplicationsNewRoute: AdmissionsApplicationsNewRoute,
  AdmissionsEnquiriesEnquiryIdRoute: AdmissionsEnquiriesEnquiryIdRoute,
  AdmissionsEnquiriesNewRoute: AdmissionsEnquiriesNewRoute,
  AdmissionsAdmittedIndexRoute: AdmissionsAdmittedIndexRoute,
  AdmissionsApplicationsIndexRoute: AdmissionsApplicationsIndexRoute,
  AdmissionsEnquiriesIndexRoute: AdmissionsEnquiriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
